# Generated by Django 4.2.11 on 2024-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kombuchacalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='starter_type',
            field=models.CharField(choices=[('k', 'Kombucha'), ('j', 'Jun')], default='k', max_length=1),
        ),
    ]
