# Generated by Django 4.2.11 on 2024-06-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kombuchacalendar', '0002_batch_starter_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
